spring:
  application:
    name: creev

  datasource:
    url: jdbc:h2:mem:creev;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=3000
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      jakarta.persistence.lock.timeout: 3000
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
